
image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки


install:
  # запускаем SUT (& означает, что в фоновом режиме - не блокируем терминал для запуска тестов)
  - docker version
  - docker-compose up
  - java -Dspring.datasource.url=jdbc:mysql://192.168.99.100:3306/app -jar aqa-shop.jar &

build_script:
  - chmod +x gradlew
  - ./gradlew-Ddb.url=jdbc:mysql://192.168.99.100:3306/app test --info "-Dselenide.headless=true"